version: '3'

services:
  web:
    build: .
    image: bpidus
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    image: bpidus
    command: python manage.py migrate --noinput
    volumes:
      - .:/app

